### PR TITLE
feat: Shared Routes

### PR DESCRIPTION
**Pull request by EvanBacon**
# Motivation

- Apps like Twitter, Spotify, Instagram, etc. allow users to access the same screen from multiple tabs while sharing the same URL on web.

# Execution

> Everything here is experimental.

- Allow conflicting routes to be defined, conflicting routes will use the same URL but can be presented in different locations.
- Introduce new clone syntax `(alpha, beta)` which creates multiple copies of a group.
- Change fragment syntax behavior so the name of the fragment becomes the initial route name when a child matches the name. e.g. `(alpha)/alpha.js` will be the initial route.
  - This system accounts for collapsing `index` when no matching child route can be found.
- Make initial routes the first screen in a layout unless specified otherwise. The previous behavior was to use index/alphabetic sorting. This is a more intentional design. The use of `<Screen />` components can still be used to control the exact order.
  - Example: `(alpha, beta)/alpha.js` will default to showing `(alpha)/alpha.js` and `(beta)/beta.js` as initial routes.
- State rehydration (deep linking, page refreshing) will use the shortest possible state. For example, if `(alpha, beta)/alpha.js` and the user refreshes from `/beta`, `(beta)/beta.js` will be used instead of `(alpha)/alpha -> (alpha)/beta`.
  - State rehydration with clone syntax will use the first group in the order, e.g. `(alpha, beta)` will default to routes in `(alpha)/*`. 
- Linking now supports relative syntax `href="./alpha"` to navigate to the path matching `alpha` relative to the file. Whereas absolute syntax `href="/alpha"` will go to the default route matching `/alpha` (i.e. state rehydration).
- Layout Routes (`_layout`) now get a `segment` prop which can be used to deduce which segment is being rendered. This should be used with cloned groups. This may be replaced with a hook to follow the other conventions.

# Test Plan

This change adds a highly opinionated layer on top of Expo Router, extensive user testing will be required.

## Twitter example

```
app/
  (feed)/
    _layout.js -> Tab
    (feed, explore, [user])/
      _layout.js -> Stack
      feed.js -> default on feed tab
      explore.js -> default on explore tab
      compose.js -> modal
      [user]/
        index.js -> default on user tab
    (messages) -> A unique stack
      _layout.js -> Stack
      messages.js
      [user]/
        index.js -> re-export the other user profile
```

### CODE REVIEW

**Comment by nandorojo** [comment]
For the Twitter messages example: if you open a tweet from a message, would you stay in the same tab?

**Comment by EvanBacon** [comment]
@nandorojo yes, it should.

**Comment by EvanBacon** [comment]
@karlhorky spaces or not, either is supported. May also consider changing the delimiter to `|`.

**Comment by EvanBacon** [comment]
Not perfect but close enough for general beta testing

**Pull request merged**
