### PR TITLE
Add Guest List app

### PR DESCRIPTION
**Pull request by karlhorky**
# Motivation

Show example of Guest List app with Expo Router

# Execution

Added a link to the readme

# Test Plan

- Check whether the link works
- Check whether the repo is high enough quality

### CODE REVIEW

**Comment by EvanBacon** [comment]
Please fix up the app:

- app.json is invalid https://github.com/hola-soy-milk/upleveled-react-native-expo/blob/c884c9c432e18f6be5212dd484610fa168117840/guest-list-mobile/app.json#L5
- button is clipped by notch
- App.tsx is extranous
- example isn't using Layout routes, instead opting to use a custom header component.

Simulator Screen Shot - iPhone 14 Pro Max - 2023-02-28 at 14 37 16

**Comment by karlhorky** [comment]
Thanks for the feedback! I've opened this issue for the fixes:

- https://github.com/hola-soy-milk/upleveled-react-native-expo/issues/2

**Comment by hola-soy-milk** [comment]
Thanks for the feedback.

Could you please elaborate: Should I remove `App.tsx`?

Thanks in advance!

**Comment by hola-soy-milk** [comment]
Thanks for the feedback, @EvanBacon.

Could you please take another look at the app?

**Comment by karlhorky** [comment]
Thanks both for the work and the merge!

**Pull request merged**
