### PR TITLE
feat: add ability to redirect child routes

### PR DESCRIPTION
**Pull request by EvanBacon**
- Add ability to prevent routes from rendering for usage in authentication and related: https://github.com/expo/router/discussions/20
- resolves https://github.com/expo/router/issues/14
- Issue with this approach is how it's tied to the client-side, this means it won't scale to support pre-rendering very well.

```
app/
  (root)/ # The children can be fragments, layouts, etc.
    home.js
    login.js
  (root).js 
```

`app/(root).js`
```tsx
import { Stack } from 'expo-router';

function Root() {
  const auth = useAuth();
  return (
    <Stack>
      <Stack.Screen name="home" redirect={!auth} />
      <Stack.Screen name="login" redirect={!!auth} />
    </Stack>
  )
}
```

## Considerations

- Maybe we should move `hidden` into the `options` for a screen.
  - We'll probably keep the property out of `options` for now.
- Is `hidden` a good name for this?
  - ~~Looks like `forbidden` (403) or `unauthorized` (401) might be better prop names.~~
  - We will be using `redirect` as it most closely resembles the behavior.
- Does the pattern of locking each route make sense? An alternative could be to have a special case to only allow a single screen. I'd personally opt away from this as it introduces a new concept for populating a layout with child routes.
  - Seems like implementing a `Switch` layout, which is built on top of the proposed functionality would be a nice way to continue.
- The default behavior of React Navigation is to redirect an unavailable route to the nearest available child route in a layout. 
  - Alternatively, we could attempt to override this and cause the request to 404. My personal take, if a developer wants to control the behavior of a particular route and make it 404, they should keep the route visible (`hidden={false}`) and control the presentation inside each particular route, e.g. detect if unauthenticated in a protected route and manually export a new component which indicates the protected status.
  - If the alternative is accepted, then the proposed behavior will not exist in any capacity. This is good cuz less behavior, and bad cuz the behavior has some value.

### CODE REVIEW

**Comment by trin4ik** [comment]
good news, we need acessability on screen/stack level. for auth, for lock some screens depending on user role/level, for AB tests, feature-flags and other patterns.

> Is hidden a good name for this?
i think `forbidden` is more semantically. 
and there is no feeling that it should work back? no `hidden` or `forbidden`, but `accessible` or `available` with default `true`?

> Maybe we should move hidden into the options for a screen.
there will be no confusion with options from react-navigation? what if "tomorrow" react-navigation team add this options for other cases?

**Comment by EvanBacon** [comment]
> i think `forbidden` is more semantically.

Good idea. I don't personally like the word `forbidden` but I do agree it's more semantically correct, which I think matters more.

> and there is no feeling that it should work back? 

I think maybe this could be a special kind of navigator that utilizes the `hidden` / `forbidden` prop. Maybe like a `Switch` which would be a special stack navigator that only allows one possible to child route to be accessible at any given time. We can implement this later. 

> ...react-navigation team add this options for...

@trin4ik React Navigation is an Expo project, essentially the same team. We'd be able to coordinate upstreaming changes fairly easily.

**Comment by trin4ik** [comment]
> @trin4ik React Navigation is an Expo project, essentially the same team. We'd be able to coordinate upstreaming changes fairly easily.

yes i known ) amazing peoples, who made expo, react-navigation, reanimated etc. react-native without yours projects — webview 2.0, no more. i’m your big fan.
but that's not a guarantee of confusion

**Comment by chrisdrackett** [comment]
I generally handle this in a way that after auth the user can see the route they had been trying to access. Currently this can be via a redirect and url parameter *or* keeping the route and rendering a login screen.

I also wonder if something like `authRequired` is better for a prop? I'm currently having a hard time thinking of other uses for `hidden` or `forbidden` that feel like more general terms.

**Comment by EvanBacon** [comment]
> something like `authRequired` is better for a prop

@chrisdrackett I'm open to using the `authorized` name, but this would require the prop to default to `true` which I'm not a fan of API-wise. By default, we always render all child routes as this is more intuitive for the majority of cases, therefore we need a property that indicates `value={true}` disables the route. So perhaps `unauthorized` could work.

> I generally handle this in a way that after auth the user can see the route they had been trying to access. Currently this can be via a redirect and url parameter or keeping the route and rendering a login screen.

I think there will be two different popular mechanisms for authenticating:

- Layout controls children: This is what we're introducing in this PR. This system will be the fastest and easiest to setup.
-  Children redirect as needed: Each child will have some logic for determining if the route is protected then manually redirect or present a 403-type UI as needed. This will allow for more customization but could end up having some leaky routes. Devs could utilize this pattern to manually redirect while setting a query param to redirect back after complete.

**Comment by Albert-Gao** [comment]
TBH, This looks just like a sugar implementation on top of what we currently have... It's like a inject the code based route model to a file based route model...and you simply have to apply this prop to all the protected routes, it's more verbose than the current react-navigation way of doing the top-level swapping which only happens once. 

And if we need to duplicate all the state of the modules here again, what's the point of having file base navigation in the 1st place...😄

Naming wise,`hidden` is better than `authorized `, since there are way too many this kind of application states, and `authorized` is just one of them. What about EmailVerify? In which a user is authed but has no right to access the content since he is not email verified. What about RBAC based routing? Apply of these changes 1 by 1? The real-world use cases are far more complex than this. Do not solve a case for `authorized` alone, there is no such thing, it's about application level state routes swapping. It's not something the framework should worry about.

If you want to handle such an application level state which impacts the route, categorizing the screens are way easier to reason about, rather than duplicating the module files again in the code and defining them 1 by 1...

Also, the problem with `hidden` is it has less flexibility than the `< Protected>` route, since it's a prefixed feature baked into the framework which you have no control against, and here comes the `beforeHidden` and `afterHidden` prop for more control?  🤣 

If you adopt a model, embracing the model rather than applying the old way to the new thing, the API would be weird if you try to bring all the old stuff back.

What's more troublesome is:

> Trying to solve an application level problem on the framework level

This would lead to nothing but a rabbit hole. 😄

**Comment by bndkt** [comment]
@EvanBacon mentioning "Switch" made something click for me. Sure we could operate on single routes using "hidden", "forbidden," or whatever it should be called, but for many implementations, those would be used to implement a best practice recommended for auth by many (see https://reactnavigation.org/docs/auth-flow/ and https://kentcdodds.com/blog/authentication-in-react-applications as examples) where within the navigation tree there at some point there is only one valid path at a given time based on factors like auth or loading state.

So for this pattern, I think the ideal solution would indeed be a "Switch" navigator that's based on Stack/NativeStack and that only activates one single route out of a number of options based on some external factor (could be implemented with a callback). It could look like this:

(auth).tsx

```ts
export default function Layout() {
  const { isSignedIn, isSignedOut } = useAuth();

  function resolveSwitch() {
    return isSignedIn ? "(authenticated)" : isSignedOut ? "signIn" : "loading";
  }

  return (
    <Switch screenOptions={{ headerShown: false }} resolve={resolveSwitch}>
      <Switch.Screen name="loading" />
      <Switch.Screen name="signIn" />
      <Switch.Screen name="(context)" />
    </Switch>
  );
}
```

And, with file-based routing, defining the routes would of course not even be necessary, so it could be as easy as:

```ts
export default function Layout() {
  const { isSignedIn, isSignedOut } = useAuth();

  return (
    <Switch
      screenOptions={{ headerShown: false }}
      resolve={() =>
        isSignedIn ? "(authenticated)" : isSignedOut ? "signIn" : "loading"
      }
    />
  );
}
```

**Comment by izakfilmalter** [comment]
I have basically done the switch option in my app. It's what makes the most sense to me. There are way to many possible states as pointed out by @Albert-Gao. The con of the switch is that it kinda kills the file system ethos.

**Comment by EvanBacon** [comment]
## Update

After discussing our findings and the feedback more with my team it sounds like we should change `forbidden` to `redirect` and enable it to accept `true | string` where `true` redirects to the next available sibling route (current behavior) and a `string` will provide a more controlled redirect in the case of multiple available routes (we'll have to build this in custom).

The issue with `unauthorized` is that you tend to get this on the web when the user is already authorized and attempts to visit a page they cannot access.

The issue with `forbidden` is that it implies you should have some sort of error state or page that indicates the route is unavailable (similar to what we do with 404/unmatched).

Given everything we currently know about the issue, I think this is the clearest, most expressive, and cross-platform behavior we can achieve.

## Further work

After this lands, we can introduce the `Switch` layout which would accept a single prop for choosing the only available child route. The Switch layout will be built on top of the functionality we're introducing in this PR. I imagine Switch will be how most developers implement basic authentication with Expo Router.

After that, we'll want to document how a developer sets up a more complex and robust experience where each parent route implements custom redirect logic without the Switch layout. This would be analogous to something like Twitter or LinkedIn where a user can still see a post but they'll be prompted to log in using navigational elements.

**Comment by trin4ik** [comment]
@EvanBacon wow, `redirect` look like really most expressive!

at now i playing with #27, its about `initialRouteName` in [linking config](https://reactnavigation.org/docs/configuring-links/#rendering-an-initial-route) (needed for preload true index, before render modals, for example). and i think we need to "known" about redirects in [/src/ContextNavigationContainer.tsx](https://github.com/expo/router/blob/8ce4c3e1582c430c0f67ff9cdffeda4e4fcd15b0/packages/expo-router/src/ContextNavigationContainer.tsx) ([useLinkingConfig](https://github.com/expo/router/blob/8ce4c3e1582c430c0f67ff9cdffeda4e4fcd15b0/packages/expo-router/src/getLinkingConfig.ts#L93) -> [useRoutesContext](https://github.com/expo/router/blob/8ce4c3e1582c430c0f67ff9cdffeda4e4fcd15b0/packages/expo-router/src/context.ts#L12) <- [getRoutes](https://github.com/expo/router/blob/8ce4c3e1582c430c0f67ff9cdffeda4e4fcd15b0/packages/expo-router/src/getRoutes.ts#L150)) for true logic with redirects, when app starts from deep link

**Comment by bndkt** [comment]
@EvanBacon sounds great!

**Comment by EvanBacon** [comment]
Redirect as a string is going to be a bit tricky to implement, I'm going to publish just boolean support so some people can get unblocked. Opened a linear task internally to track adding string support.

**Pull request merged**
